export const SLIDE_DURATION_MS = 10_000;

export const STORY_BEATS = [
  {
    id: "opportunity",
    kicker: "A missed workplace opportunity",
    title: "The coworker who could change your day may be one desk away.",
    body: "A useful skill. A fresh perspective. A connection you have not made yet.",
    durationMs: SLIDE_DURATION_MS,
    mediaType: "photo",
    media: "walk",
    alt: "Two fictional coworkers walking through a bright office corridor",
    disclosure: "Fictional demo characters",
    tone: "mint",
  },
  {
    id: "friction",
    kicker: "But connection is left to chance",
    title: "Busy days make workplace circles smaller.",
    body: "We pass each other every day while practical knowledge stays trapped inside teams.",
    durationMs: SLIDE_DURATION_MS,
    mediaType: "photo",
    media: "coffee",
    alt: "Two fictional coworkers talking over coffee in an office pantry",
    disclosure: "Fictional demo characters",
    tone: "coral",
  },
  {
    id: "intent",
    kicker: "SideSpark starts with one simple choice",
    title: "What kind of spark do you need today?",
    body: "Swap something useful—or meet someone beyond your usual circle.",
    durationMs: SLIDE_DURATION_MS,
    mediaType: "reference",
    media: "intent",
    alt: "SideSpark interface offering Skill Swap and Social Connect",
    tone: "sun",
  },
  {
    id: "format",
    kicker: "Make it fit the working day",
    title: "Pick a break. Keep it human.",
    body: "Coffee. Walk. Lunch. Or a 15-minute Desk Break.",
    durationMs: SLIDE_DURATION_MS,
    mediaType: "reference",
    media: "journey",
    alt: "SideSpark journey showing coffee, walk, and lunch break choices",
    tone: "mint",
  },
  {
    id: "match",
    kicker: "Then SideSpark creates the first easy moment",
    title: "One thing in common. One thing to discover.",
    body: "A safe match gives both people a practical quest they can begin without an awkward first move.",
    durationMs: SLIDE_DURATION_MS,
    mediaType: "photo",
    media: "skill",
    alt: "Two fictional coworkers sharing a practical skill beside a laptop",
    disclosure: "Fictional demo characters",
    tone: "coral",
  },
  {
    id: "payoff",
    kicker: "A small break becomes a visible connection",
    title: "Take a break. Find your spark.",
    body: "No sign-in. Just a real reason to start talking.",
    durationMs: SLIDE_DURATION_MS,
    mediaType: "product",
    media: "complete",
    alt: "SideSpark product screen in its deep-indigo visual system",
    tone: "sun",
  },
];

export const TOTAL_DURATION_MS = STORY_BEATS.reduce(
  (total, beat) => total + beat.durationMs,
  0,
);
